#Author Son [Joe] Nguyen
# I pledge my Honor that I have abided by the Stevens Honor System

#the GNU C Compiler
$(CC) = gcc

final: main.o
	$(CC) main.o -o a.out

main.o: main.c
	$(CC) -c main.c


clean:
	rm -f *.o a.out
